apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: freqtuner
  namespace: ${NAMESPACE}
  labels:
    app: freqtuner
spec:
  selector:
    matchLabels:
      app: freqtuner
  template:
    metadata:
      labels:
        app: freqtuner
      annotations:
        nvidia.com/gpu-driver-capabilities: "compute,utility,compat32"
    spec:
      serviceAccountName: freqtuner
      nodeSelector:
        nvidia.com/gpu: "true"
      containers:
      - name: manager
        image: ${IMAGE_REGISTRY}/freqtuner:${IMAGE_TAG}
        imagePullPolicy: Always
        args:
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
              - ALL
          allowPrivilegeEscalation: true
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility,video"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=11.0"
        - name: NVIDIA_MIG_CONFIG_DEVICES
          value: "all"
        volumeMounts:
        - name: nvidia-management
          mountPath: /usr/bin/nvidia-smi
        - name: nvidia-libraries
          mountPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
      initContainers:
      - name: gpu-init
        image: nvidia/cuda:11.0-base
        command: ["/bin/sh"]
        args:
        - -c
        - |
          nvidia-smi -pm 1 || true
          nvidia-smi --query-gpu=gpu_name,gpu_uuid,compute_mode,persistence_mode --format=csv
          chmod 666 /dev/nvidia* || true
        securityContext:
          privileged: true
      volumes:
      - name: cpu-freq
        hostPath:
          path: /sys/devices/system/cpu
      - name: nvidia-bindings
        hostPath:
          path: /usr/local/nvidia
      - name: nvidia-devices
        hostPath:
          path: /dev
      - name: nvidia-caps
        hostPath:
          path: /dev/nvidia-caps
      - name: nvidia-libs
        hostPath:
          path: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
      - name: nvidia-smi
        hostPath:
          path: /usr/bin/nvidia-smi
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule