apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: freqtuning-recommender-rolebinding
subjects:
- kind: ServiceAccount
  name: freqtuning-recommender
  namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: freqtuning-recommender-role
  apiGroup: rbac.authorization.k8s.io 