//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFrequencySpec) DeepCopyInto(out *GPUFrequencySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFrequencySpec.
func (in *GPUFrequencySpec) DeepCopy() *GPUFrequencySpec {
	if in == nil {
		return nil
	}
	out := new(GPUFrequencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFrequencies) DeepCopyInto(out *NodeFrequencies) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFrequencies.
func (in *NodeFrequencies) DeepCopy() *NodeFrequencies {
	if in == nil {
		return nil
	}
	out := new(NodeFrequencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeFrequencies) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFrequenciesList) DeepCopyInto(out *NodeFrequenciesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeFrequencies, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFrequenciesList.
func (in *NodeFrequenciesList) DeepCopy() *NodeFrequenciesList {
	if in == nil {
		return nil
	}
	out := new(NodeFrequenciesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeFrequenciesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFrequenciesSpec) DeepCopyInto(out *NodeFrequenciesSpec) {
	*out = *in
	if in.GPUFrequencies != nil {
		in, out := &in.GPUFrequencies, &out.GPUFrequencies
		*out = make([]GPUFrequencySpec, len(*in))
		copy(*out, *in)
	}
	if in.CPUFrequencies != nil {
		in, out := &in.CPUFrequencies, &out.CPUFrequencies
		*out = make([]CPUFrequencySpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFrequenciesSpec.
func (in *NodeFrequenciesSpec) DeepCopy() *NodeFrequenciesSpec {
	if in == nil {
		return nil
	}
	out := new(NodeFrequenciesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFrequenciesStatus) DeepCopyInto(out *NodeFrequenciesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFrequenciesStatus.
func (in *NodeFrequenciesStatus) DeepCopy() *NodeFrequenciesStatus {
	if in == nil {
		return nil
	}
	out := new(NodeFrequenciesStatus)
	in.DeepCopyInto(out)
	return out
}
